name: Auto Merge All PRs

on:
  schedule:
    # - cron: '55 23 * * 5'  # 매주 금요일 23시 55분
    - cron: '36 7 * * 6'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch and Merge PRs
        run: |
          git config user.name "won4885"
          git config user.email "won4885.dev@gmail.com"
          git fetch origin "+refs/pull/*/head:refs/remotes/origin/pr/*"
          
          # Loop through all remote PR branches and merge them
          for branch in $(git for-each-ref --format '%(refname:short)' refs/remotes/origin/pr/*); do
            pr_number=$(echo $branch | cut -d '/' -f 4)
            git checkout $branch
            git merge origin/main --no-ff -m "Merge PR #$pr_number"
            git push origin HEAD:main
          done
