name: Merge All PRs

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  merge:
    name: Merge PRs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull requests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prList = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            for (const pr of prList.data) {
              try {
                await github.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number
                });
                console.log(`Merged PR #${pr.number}`);
              } catch (error) {
                console.log(`Error merging PR #${pr.number}: ${error.message}`);
              }
            }
