name: Merge Pull Request

on:
  schedule:
    - cron: '55 23 * * 5'  # 매주 금요일 23시 55분

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge pull request
        run: |
          git config user.name "won4885"
          git config user.email "2dcoder@naver.com"
          git fetch origin pull/$/merge --depth=1
          git merge FETCH_HEAD --no-commit
          git commit -m "Merge pull request #$ - $"
          git push
